# Generated by Django 3.1.2 on 2020-10-04 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('workingHour', models.CharField(max_length=250)),
                ('serviceType', models.CharField(choices=[('Hospital', 'Hospital'), ('Service', 'Service'), ('Salon', 'Salon')], max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('zipCode', models.IntegerField()),
                ('mapLink', models.CharField(max_length=250)),
                ('others', models.CharField(max_length=250)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
