# Generated by Django 3.1.2 on 2020-10-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201004_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenNoHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenNo', models.IntegerField(default=0)),
                ('timeStamp', models.DateField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.company')),
            ],
        ),
    ]
